---
- name: Setup Dotfiles
  hosts: localhost
  connection: local

  roles:
    - role: geerlingguy.mac.homebrew
      tags: homebrew
      when: ansible_distribution == "MacOSX"

    - role: markosamuli.asdf
      tags: asdf

    - role: local.git
      tags: git

    - role: local.tmux
      tags: tmux

    - role: local.fish
      tags: fish

    - role: local.kitty
      tags: kitty

    - role: local.neovim
      tags: neovim

    - role: local.op
      tags: op
