---
- name: Setup Dotfiles
  hosts: localhost
  connection: local

  roles:
    - role: markosamuli.asdf
      tags: asdf

    - role: local.git
      tags: git

    - role: local.neovim
      tags: neovim

    - role: local.kitty
      tags: kitty
