---
- name: Setup Dotfiles
  hosts: localhost
  connection: local
  vars:
    fzf_version: 0.27.2
    asdf_init_shell: false
    asdf_plugins:

      - name: awscli
        global: 2.2.13
        versions:
          - 2.2.13

      - name: bat
        global: 0.18.1
        versions:
          - 0.18.1

      - name: exa
        global: 0.10.1
        versions:
          - 0.10.1

      - name: fd
        global: 8.2.1
        versions:
          - 8.2.1

      - name: fzf
        global: "{{ fzf_version }}"
        versions:
          - "{{ fzf_version }}"

      - name: helm
        global: 3.6.1
        versions:
          - 3.6.1

      - name: kubectl
        global: 1.21.2
        versions:
          - 1.21.2

      - name: kubectx
        global: 0.9.3
        versions:
          - 0.9.3

      - name: python
        global: miniconda3-latest
        versions:
          - miniconda3-latest
          - miniconda3-4.7.12

      - name: ripgrep
        global: 13.0.0
        versions:
          - 13.0.0

      - name: ruby
        global: 3.0.1
        versions:
          - 3.0.1

      - name: terraform
        global: 1.0.0
        versions:
          - 1.0.0

  roles:
    - markosamuli.asdf
