---
- name: Setup Dotfiles
  hosts: localhost
  connection: local

  roles:
    - role: local.kitty
      tags: kitty

    - role: local.fish
      tags: fish

    - role: local.git
      tags: git

    - role: local.tmux
      tags: tmux

    - role: local.neovim
      tags: neovim

    - role: markosamuli.asdf
      tags: asdf

