- name: faen.bash
  src: https://gitlab.com/faen/bash.git
  scm: git
  version: v1.0.0

- name: faen.fzf
  src: https://gitlab.com/faen/fzf.git
  scm: git
  version: v1.0.0

- name: faen.git
  src: https://gitlab.com/faen/git.git
  scm: git
  version: v2.0.0

- name: faen.gpg
  src: https://gitlab.com/faen/gpg.git
  scm: git
  version: v1.0.0

- name: faen.less-pcre
  src: https://gitlab.com/faen/less-pcre.git
  scm: git
  version: v1.0.0

- name: faen.nvim
  src: https://gitlab.com/faen/nvim.git
  scm: git
  version: v2.0.0

- name: faen.packages
  src: https://gitlab.com/faen/packages.git
  scm: git
  version: v1.0.0

- name: faen.tmux
  src: https://gitlab.com/faen/tmux.git
  scm: git
  version: v1.0.0
