---

- name: Lookup config dirs
  local_action:
    module: find
    paths: "{{ role_path }}/files"
    recurse: true
    file_type: directory
  register: full_directories_path

- name: Lookup config files
  local_action:
    module: find
    paths: "{{ role_path }}/files"
    recurse: true
    pattern: "*.fish"
  register: full_files_path

- name: Set paths relative to role
  set_fact:
    directories: "{{ full_directories_path.files | map(attribute='path') | map('regex_replace', '^' + role_path + '/files/', '') }}"
    files: "{{ full_files_path.files | map(attribute='path') | map('regex_replace', '^' + role_path + '/files/', '') }}"

- name: Create configuration directories
  file:
    name: "~/.config/fish/{{ item }}"
    state: directory
    recurse: true
  loop: "{{ directories }}"
  tags:
    - config

- name: Write configuration files
  copy:
    src: "{{ item }}"
    dest: "~/.config/fish/{{ item }}"
  loop: "{{ files }}"
  tags:
    - config

- name: Check if fish is installed
  command: which fish
  register: fish
  ignore_errors: true
  tags:
    - install
    - update

- name: Check if fisher is installed
  stat:
    path: ~/.config/fish/functions/fisher.fish
  register: fisher
  tags:
    - install
    - update

- name: Install fisher
  shell:
    cmd: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
    executable: "{{ fish.stdout }}"
  register: fisher_install
  when:
    - fish.rc == 0
    - not fisher.stat.exists
  tags:
    - install
    - update

- name: Write fish_plugins
  copy:
    src: fish_plugins
    dest: ~/.config/fish/fish_plugins
  tags:
    - config

- name: Install and update plugins
  shell:
    cmd: fisher update
    executable: "{{ fish.stdout }}"
  when:
    - fish.rc == 0
    - fisher.stat.exists or fisher_install.changed
  tags:
    - install
    - update
