---
- name: Lookup config dirs
  local_action:
    module: find
    paths: "{{ role_path }}/files"
    recurse: true
    file_type: directory
  register: full_directories_path
  tags:
    - config

- name: Lookup config files
  local_action:
    module: find
    paths: "{{ role_path }}/files"
    recurse: true
    pattern: "*.fish"
  register: full_files_path
  tags:
    - config

- name: Set paths relative to role
  set_fact:
    directories: "{{ full_directories_path.files | map(attribute='path') | map('regex_replace', '^' + role_path + '/files/', '') }}"
    files: "{{ full_files_path.files | map(attribute='path') | map('regex_replace', '^' + role_path + '/files/', '') }}"
  tags:
    - config

- name: Create config directories
  file:
    name: "~/.config/fish/{{ item }}"
    state: directory
    recurse: true
  loop: "{{ directories }}"
  tags:
    - config

- name: Write config files
  copy:
    src: "{{ item }}"
    dest: "~/.config/fish/{{ item }}"
  loop: "{{ files }}"
  tags:
    - config

- name: Install fish on macOS
  import_tasks: install-macos.yml
  when:
    - ansible_distribution == "MacOSX"
  tags:
    - install

- name: Install fish on Ubuntu
  import_tasks: install-ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
  tags:
    - install

- name: Check if fish is installed
  command: which fish
  register: fish
  ignore_errors: true
  changed_when: false
  tags:
    - install
    - config
    - update

- name: Check if fisher is installed
  stat:
    path: ~/.config/fish/functions/fisher.fish
  register: fisher
  tags:
    - install
    - config
    - update

- name: Ubuntu | Install curl on Ubuntu
  apt:
    name: curl
    state: present
  become: true
  when:
    - ansible_distribution == "Ubuntu"
  tags:
    - config

- name: Install fisher
  shell:
    cmd: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
    executable: "{{ fish.stdout }}"
  register: fisher_install
  when:
    - fish.rc == 0
    - not fisher.stat.exists
  tags:
    - install
    - update

- name: Write fish_plugins
  copy:
    src: fish_plugins
    dest: ~/.config/fish/fish_plugins
  tags:
    - config

- name: Install and update plugins
  shell:
    cmd: fisher update
    executable: "{{ fish.stdout }}"
  when:
    - fish.rc == 0
    - fisher.stat.exists or fisher_install.changed
  tags:
    - install
    - update

- name: Set universal variables
  shell:
    cmd: |
      set --universal FZF_LEGACY_KEYBINDINGS 0
      set --universal FZF_FIND_FILE_IGNORE "{.git,.terraform,node_modules,vendor,elm-stuff,deps,_build,target,pkg,Library,.Trash}"
      set --universal FZF_FIND_FILE_COMMAND "fd --type file --exclude '$FZF_FIND_FILE_IGNORE'"
      set --universal FZF_CD_COMMAND "fd --type directory --exclude '{pkg,Library}'"
      set --universal FZF_CD_WITH_HIDDEN_COMMAND "fd --type directory --exclude '{pkg,Library,.Trash}'"
    executable: "{{ fish.stdout }}"
  when:
    - fish.rc == 0
  tags:
    - config
