---
- name: Create required directories
  file:
    name: "{{ item }}"
    state: directory
  loop:
    - ~/.cache
    - ~/.config/nvim/backups
    - ~/.config/nvim/swaps
    - ~/.config/nvim/undo
  tags:
    - config

- name: macOS | Install neovim
  homebrew:
    name: neovim
    state: present
  when:
    - ansible_distribution == "MacOSX"
  tags:
    - install

- name: Install neovim on Ubuntu
  import_tasks: install-ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
  tags:
    - install

- name: Install dein plugin manager
  git:
    repo: https://github.com/Shougo/dein.vim
    dest: ~/.cache/dein/repos/github.com/Shougo/dein.vim
    depth: 1
  tags:
    - config

- name: Write ~/.config/nvim/init.vim
  template:
    src: init.vim.j2
    dest: ~/.config/nvim/init.vim
  tags:
    - config

- name: Check if neovim is installed
  command: which nvim
  register: nvim
  ignore_errors: true
  changed_when: false
  tags:
    - config

- name: Install and Update plugins
  command: >
    nvim --headless +'
    if dein#check_install()
      call dein#install()
    endif
    call dein#update()'
    +qa!
  when:
    - nvim.rc == 0
  tags:
    - config
