---
- name: Create .config/kitty
  file:
    name: ~/.config/kitty
    state: directory
  tags:
    - config

- name: Write .config/kitty/kitty.conf
  template:
    src: kitty.conf.j2
    dest: ~/.config/kitty/kitty.conf
  tags:
    - config

- name: Arch | Install kitty
  pacman:
    name: kitty
    state: present
  become: true
  when:
    - ansible_distribution == "Archlinux"

- name: macOS | Install kitty
  homebrew_cask:
    name: kitty
    state: present
  when:
    - ansible_distribution == "MacOSX"

- name: Ubuntu | Install kitty
  apt:
    name: kitty
    state: present
  become: true
  when:
    - ansible_distribution == "Ubuntu"
